version: "3.8"
services:
    nuxt:
        build: .
        restart: always
        ports:
          - "3333:3333"
        command:
          "npm run dev"
    
    nginx:
        image: nginx
        ports:
          - "80:80"
        volumes:
          - ./nginx:/etc/nginx/conf.d
        depends_on:
          - nuxt
    
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db

volumes:
    mongodb:
    node_modules:
    
