version: "3.8"
services:
    app:
        image: node:12-alpine
        container_name: secret-app
        build: .
        command: npm run dev
        volumes:
            - .:/usr/src/app
            - /app/node_modules/
        ports:
            - "3000:3000"
        environment:
            HOST: 0.0.0.0
        depends_on:
            - mongo

    
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db

volumes:
    mongodb:
    node_modules:
    
