version: "3.8"
services:
    app:
        image: node:12-alpine
        container_name: secret-app
        build: .
        command: npm run dev
        volumes:
            - .:/usr/src/app
            - /app/node_modules/
        ports:
            - "3000:3000"
        environment:
            HOST: 0.0.0.0
        depends_on:
            - mongo

    
    mongo:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_DATABASE: secret-db
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/data/secret-db

volumes:
    mongodb_data:
    node_modules:
    
